### PR TITLE
feat: Profile Page

### PR DESCRIPTION
**Pull request by ManishBisht777**

### CODE REVIEW

**Comment by sboy99** [comment]
@Somidh please allow us to see vercel deployment

**Comment by Aadarsh805** [comment]
@sboy99 invited to team, ig now you'll have be able to see deployment

**Comment by Aadarsh805** [comment]
@sboy99 failed because of some eslint check

**Comment by Aadarsh805** [comment]
maybe we should disable those checks otherwise we wont be able to preview deployment

**Comment by ManishBisht777** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaah eslint

**Review by Aadarsh805 — APPROVED** [review]
lgtm

**Pull request merged**
